name: Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]

env:
  GCP_PROJECT_ID: prod-mksv5m2rtl7g
  GAR_LOCATION: us-central1
  GAR_REPOSITORY: afurze-container-repo
  IMAGE_NAME: analytics-docs
  JOB_NAME: analytics-jobs-job

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: 'Docker Login to GAR'
        uses: 'docker/login-action@v3'
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: 'Build and Push'
        uses: 'docker/build-push-action@v5'
        with:
          push: true
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

  deploy-and-run:
    # This job will only run after 'build-and-push' is successful
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
      
      # This step deploys the job definition
      - id: 'deploy'
        name: 'Deploy Cloud Run Job'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          job: ${{ env.JOB_NAME }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          region: ${{ env.GAR_LOCATION }}

      # This step executes the job
      - name: 'Execute Cloud Run Job'
        run: |-
          gcloud run jobs execute ${{ env.JOB_NAME }} --region ${{ env.GAR_LOCATION }} --wait